const connection = require('./cassandraConnection.js');

/* BUILD ALL OF YOUR QUERY FUNCTIONS HERE */

// POST FOR A PRODUCT

// GET RESPONDS WITH A SPECIFIC PRODUCT

// PUT UPDATES A SPECIFIC PRODUCT

// DELETE DELETES A SPECIFIC PRODUCT

